# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            A computational system for ancient Greek
tagline:          'Greek orthography, phonology, morphology, and epic hexameter'
description:      'Specification of a computational system for working with ancient Greek, and implementations of the specification in code libraries for the JVM'
baseurl: '/greeklang/'


author:
  name:           'Neel Smith'


paginate:         5


links:
  - title: Foundational libraries
    url: basics
  - title: Morphology
    url: morphology
  - title: Hexameter
    url: hexameter
  - title: Github project
    url: https://github.com/neelsmith/greeklang
    external: true
  - title: Neel Smith elsewhere on github
    url: http://neelsmith.github.io
    external: true
